version: '3.8'

services:
  mongo:
    container_name: mongo
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: RecordShop
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-volume:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-20
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      ATLAS_URI: mongodb://root:example@mongo:27017/
      SP_CLIENT_ID: ${SP_CLIENT_ID}
      SP_MY_USER_ID: ${SP_MY_USER_ID}
      SP_CLIENT_S: ${SP_CLIENT_S}
      API_KEY_JAMBASE: ${API_KEY_JAMBASE}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: backend
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - '5000:5000'

  frontend:
    container_name: frontend
    build:
      context: ./client/
      dockerfile: Dockerfile
    environment:
      #NODE_ENV: production
      VITE_SP_CLIENT_ID: ${VITE_SP_CLIENT_ID}
      VITE_SITE_URL_DB: ${VITE_SITE_URL_DB}
      VITE_SITE_URL: ${VITE_SITE_URL}
      VITE_PORT: ${VITE_PORT}
      VITE_EMAIL_SERVICEID: ${VITE_EMAIL_SERVICEID}
      VITE_EMAIL_TEMPLATEID: ${VITE_EMAIL_TEMPLATEID}
      VITE_EMAIL_PUBKEY: ${VITE_EMAIL_PUBKEY}
      VITE_SPOTIFY_PREVIEW_PLAYLIST_URL: ${VITE_SPOTIFY_PREVIEW_PLAYLIST_URL}
      VITE_GOOGLE_ANALYTICS: ${VITE_GOOGLE_ANALYTICS}
    healthcheck:
      test: ['CMD', 'curl', '-f', '${VITE_SITE_URL}']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: frontend
    links:
      - backend
    depends_on:
      - backend
    ports:
      - '${VITE_PORT}:${VITE_PORT}'

volumes:
  mongo-volume:
