previewsEnabled: true
services:
  - type: web
    name: record-shop-backend
    env: docker
    repo: https://github.com/devin-bushey/RecordShop.git
    region: oregon # optional (defaults to oregon)
    plan: free
    branch: main # optional (defaults to master)
    rootDir: server
    envVars:
      fromGroup: record-shop-group

envVarGroups:
  - name: record-shop-group
    envVars:
      - key: ATLAS_URI
        generateValue: true
      - key: SP_CLIENT_ID
        generateValue: true
      - key: SP_MY_USER_ID
        generateValue: true
      - key: SP_CLIENT_S
        generateValue: true
      - key: PORT
        generateValue: true
