previewsEnabled: true
services:
  - type: web
    name: record-shop-backend
    env: docker
    repo: https://github.com/devin-bushey/RecordShop.git
    region: oregon # optional (defaults to oregon)
    plan: free
    branch: main # optional (defaults to master)
    rootDir: server
    envVars:
      - key: ATLAS_URI
        sync: false
      - key: SP_CLIENT_ID
        sync: false
      - key: SP_MY_USER_ID
        sync: false
      - key: SP_CLIENT_S
        sync: false
      - key: PORT
        sync: false
    autoDeploy: true
