name: Weekly Victoria Gigs Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 8pm PDT every night

jobs:
  direct_jambase_db_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.1"

      - name: Install dependencies
        working-directory: scripts
        run: npm install

      - name: Run script
        working-directory: scripts
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          API_KEY_JAMBASE: ${{ secrets.API_KEY_JAMBASE }}
          SP_REFRESH_TOKEN: ${{ secrets.SP_REFRESH_TOKEN }}
          SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          SP_CLIENT_S: ${{ secrets.SP_CLIENT_S }}
        run: npx ts-node ./src/updateVictoriaDatabase.ts

  extract_songkick_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Delete existing pull request and branch
        id: delete_existing_pr_and_branch
        run: |
          BRANCH_EXISTS=$(curl -s -X GET -H "Authorization: Bearer $GITHUB_TOKEN" \
                        "https://api.github.com/repos/${GITHUB_REPOSITORY}/branches/weekly-vic-songkick-data")
          if [ "$BRANCH_EXISTS" != "Not Found" ]; then
            PR_NUMBER=$(curl -s -X GET -G -H "Authorization: Bearer $GITHUB_TOKEN" \
                        "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls" \
                        -d "head=${GITHUB_REPOSITORY_OWNER}:weekly-vic-songkick-data" \
                        -d "state=open" \
                        | jq -r '.[].number')
            if [ -n "$PR_NUMBER" ]; then
              curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
                "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/$PR_NUMBER"
            fi
            curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/heads/weekly-vic-songkick-data"
          fi
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.1"

      - name: Install dependencies
        working-directory: scripts
        run: npm install

      - name: Run extractSongkick
        run: npx ts-node ./scripts/src/scrapers/songkick/extractSongkick.ts > extractedVicGigs.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add extractedVicGigs.json"
          title: "Weekly Update: Extracted Victoria Songkick Data"
          body: "This PR contains the JSON array of the Songkick data extracted this week.\n\n
          It does not include Spotify data\n\n
          Please go through and edit the artist names!\n\n
          Then merge this PR to trigger the action to add Spotify data and update the database.\n\n
          <img src=\"https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDg3Y3BycmJuazM1NHlleG5qcXljZjBmdWgzNDlwNzRrb2oxNGtxcSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/blSTtZehjAZ8I/giphy.gif\" width=\"340\"/>"
          branch: weekly-vic-songkick-data
          base: main
          files: extractedVicGigs.json
          labels: weekly-update